### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by TFLQW** [viettoan151/TM_Robot_Client#1]
Hi~ Thanks for your package, but when I try to connect the TM_5 by running the **robot_test.py**, I meet this error **OSError: [Errno 101] Network is unreachable**, I have set the robot ip through TM_FLOW is 192.168.1.4 and my pc ip is 192.168.1.1, meanwhile the ping 192.168.1.4 is work in the terminal, so could you help me solve this unconnnected problem?

**Comment by viettoan151** [comment]
> Hi~ Thanks for your package, but when I try to connect the TM_5 by running the **robot_test.py**, I meet this error **OSError: [Errno 101] Network is unreachable**, I have set the robot ip through TM_FLOW is 192.168.1.4 and my pc ip is 192.168.1.1, meanwhile the ping 192.168.1.4 is work in the terminal, so could you help me solve this unconnnected problem?

Sorry, I didn't follow this git for a while.
As I remember that, we have to **Free robot** and enable **robot Server**. Robot will open server that listen on port 6188
![image](https://user-images.githubusercontent.com/22770933/131812972-b25d154a-1894-427d-ab5a-1be1e5cc23fe.png)

**Comment by viettoan151** [comment]
Hope above solution can help anyone come here!
